services:
  web:
    build: .
    container_name: comic_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/static
    env_file:
      - .env.prod
    depends_on:
      - redis

  worker:
    build: .
    container_name: comic_worker
    command: celery -A config worker -l info
    env_file:
      - .env.prod
    depends_on:
      - web
      - redis

  beat:
    build: .
    container_name: comic_beat
    command: celery -A config beat -l info #--schedule=/app/beatdata/beat.db
    env_file:
      - .env.prod
    depends_on:
      - web
      - redis
    # volumes:
    #   - beat_data:/app/beatdata

  redis:
    image: redis:7-alpine
    container_name: comic_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: comic_nginx
    depends_on:
      - web
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_data:/app/static
    ports:
      - "80:80"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

volumes:
  redis_data:
  static_data:
  beat_data: