services:
  web:
    build: .
    image: ted111712/comic_web:latest
    container_name: comic_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_data:/app/static
    env_file:
      - .env.prod
    depends_on:
      - redis

  worker:
    build: .
    image: ted111712/comic_worker:latest
    container_name: comic_worker
    command: celery -A config worker -l info
    env_file:
      - .env.prod
    depends_on:
      - web
      - redis

  beat:
    build: .
    image: ted111712/comic_beat:latest
    container_name: comic_beat
    command: celery -A config beat -l info #--schedule=/app/beatdata/beat.db
    env_file:
      - .env.prod
    depends_on:
      - web
      - redis
    # volumes:
    #   - beat_data:/app/beatdata

  redis:
    image: redis:7-alpine
    container_name: comic_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  nginx:
    image: nginx:alpine
    container_name: comic_nginx
    restart: unless-stopped
    depends_on:
      - web
      - certbot
    volumes:
      - static_data:/app/static
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

  certbot:
    image: certbot/certbot
    container_name: comic_certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  redis_data:
  static_data:
  beat_data: